export const theme = {
  colors: {
    primaryColor: "#015151",
    whiteColor: "#ffffff",
    blackColor: "#333333",
    lightgreenColor: "#079d9d",
    greyColor: "#00000059",
    ratingColor: "#ffd700",
  },
  bigScreens: {
    navBtns: "22px",
    homepageTitle: "32px",
    searchLabelFont: "18px",
    searchInputFont: "27px",
    searchLabelColor: "#00000059",
    fontsize: "30px",
    subFontsize: "28px",
    searchinputfontsize: "20px",
    optionfontsize: "22px",
    btnFontsize: "26px",
  },
  tabletAndIpadScreens: {
    navBtns: "14px",
    homepageTitle: "30px",
    searchLabelFont: "14px",
    searchInputFont: "24px",
    searchLabelColor: "#00000059",
    fontsize: "24px",
    subFontsize: "20px",
    searchinputfontsize: "12px",
    optionfontsize: "22px",
    btnFontsize: "20px",
    cardprice: "20px",
    cardlocation: "16px",
    cardhousetitle: "18px",
    carddesc: "12px",
    cardrating: "16px",
  },
  smallTabScreens: {
    navBtns: "12px",
    homepageTitle: "26px",
    searchLabelFont: "10px",
    searchInputFont: "14px",
    searchLabelColor: "#00000059",
    fontsize: "20px",
    subFontsize: "18px",
    searchinputfontsize: "12px",
    optionfontsize: "20px",
    btnFontsize: "16px",
    cardprice: "18px",
    cardlocation: "14px",
    cardhousetitle: "16px",
    carddesc: "10px",
    cardrating: "12px",
  },
  mobileScreens: {
    navBtns: "12px",
    homepageTitle: "26px",
    searchLabelFont: "8px",
    searchInputFont: "10px",
    searchLabelColor: "#00000059",
    fontsize: "14px",
    subFontsize: "12px",
    searchinputfontsize: "12px",
    optionfontsize: "20px",
    btnFontsize: "10px",
    cardprice: "18px",
    cardlocation: "14px",
    cardhousetitle: "16px",
    carddesc: "10px",
    cardrating: "12px",
  },

  cards: {
    cardMaintitle: "28px",
    cardSubtitle: "26px",
  },
};
